# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

optimal_step_size_equicorr_cpp <- function(epsilon_hat, xi_hat, I, n_obs, n_i, s, h, theta) {
    .Call(`_sandwich_boost_optimal_step_size_equicorr_cpp`, epsilon_hat, xi_hat, I, n_obs, n_i, s, h, theta)
}

optimal_step_size_AR_cpp <- function(epsilon_hat, xi_hat, I, n_obs, n_i, s, h, theta) {
    .Call(`_sandwich_boost_optimal_step_size_AR_cpp`, epsilon_hat, xi_hat, I, n_obs, n_i, s, h, theta)
}

risk_equicorr_cpp <- function(epsilon_hat, xi_hat, I, n_obs, n_i, s, theta) {
    .Call(`_sandwich_boost_risk_equicorr_cpp`, epsilon_hat, xi_hat, I, n_obs, n_i, s, theta)
}

risk_AR_cpp <- function(epsilon_hat, xi_hat, I, n_obs, n_i, s, theta) {
    .Call(`_sandwich_boost_risk_AR_cpp`, epsilon_hat, xi_hat, I, n_obs, n_i, s, theta)
}

risk_nested_cpp <- function(epsilon_hat, xi_hat, J, n_obs, n_ij, s, theta) {
    .Call(`_sandwich_boost_risk_nested_cpp`, epsilon_hat, xi_hat, J, n_obs, n_ij, s, theta)
}

ngradient_equicorr_cpp <- function(epsilon_hat, xi_hat, I, n_obs, n_i, s, theta) {
    .Call(`_sandwich_boost_ngradient_equicorr_cpp`, epsilon_hat, xi_hat, I, n_obs, n_i, s, theta)
}

ngradient_AR_cpp <- function(epsilon_hat, xi_hat, I, n_obs, n_i, s, theta) {
    .Call(`_sandwich_boost_ngradient_AR_cpp`, epsilon_hat, xi_hat, I, n_obs, n_i, s, theta)
}

ngradient_nested_cpp <- function(epsilon_hat, xi_hat, J, n_obs, n_ij, s, theta) {
    .Call(`_sandwich_boost_ngradient_nested_cpp`, epsilon_hat, xi_hat, J, n_obs, n_ij, s, theta)
}

